#!groovy

node { 
    stage 'Checkout'
        checkout scm

    stage 'Setup'
        dir('helloworld/helloworld_app') {
            sh 'npm config set registry http://registry.npmjs.org/'
            sh 'npm install'
        }

   stage 'Cleanup'
        dir('helloworld/helloworld_app') {
            echo 'prune and cleanup'
            sh 'npm prune'
            sh 'rm node_modules -rf'
        }
}
